# Sampling rate
FS = 48000


QPSK_MULTIPLIER = 30
FFT_BLOCK_LENGTH = 8196
QPSK_BLOCK_LENGTH = int((FFT_BLOCK_LENGTH-2)/2)
CYCLIC_PREFIX_LENGTH = 2048
OFDM_SYMBOL_LENGTH = CYCLIC_PREFIX_LENGTH + QPSK_BLOCK_LENGTH
