# Sampling rate
FS = 48000

# Energy of each constellation symbol
QPSK_MULTIPLIER = 30

# FFT size used for OFDM
FFT_BLOCK_LENGTH = 8192

# Number of QPSK symbols per OFDM symbol
# Not using 0 and middle (zeros) and upper half of frequencies (complex conjugates)
QPSK_BLOCK_LENGTH = (FFT_BLOCK_LENGTH - 2) // 2 #4095

CYCLIC_PREFIX_LENGTH = 2048
LOWER_FREQUENCY_BOUND = 1000
UPPER_FREQUENCY_BOUND = 9000
POSITIVE_LOWER_BIN = 2 *QPSK_BLOCK_LENGTH*LOWER_FREQUENCY_BOUND//( FS) # 170
POSITIVE_UPPER_BIN = 2 *QPSK_BLOCK_LENGTH*UPPER_FREQUENCY_BOUND//( FS) # 1535
OFDM_SYMBOL_LENGTH = CYCLIC_PREFIX_LENGTH + FFT_BLOCK_LENGTH

DATA_PER_PILOT = 1


QPSK_BLOCK_LENGTH_DATA = QPSK_BLOCK_LENGTH - POSITIVE_UPPER_BIN - POSITIVE_LOWER_BIN #2390

